services:
  rispice:
    init: true
    build:
      context: .
      args:
        REQUIREMENTS: requirements-cpu.txt

    image: rispice:cpu
    working_dir: /rispice

    stdin_open: true
    tty: true

    volumes:
      - ./.data:/rispice/.data
      - ./.models:/rispice/.models
      - ./.analysis:/rispice/.analysis
      - ./.figures:/rispice/.figures