FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    git \
    pkg-config \
    fonts-open-sans \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY requirements/ requirements/

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir \
    torch==2.10.0 \
    --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir -r requirements/base.txt

COPY . .